<?php

/**
 * TechDivision\Import\Product\Observers\UrlRewriteUpdateObserverTest
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * PHP version 5
 *
 * @author    Tim Wagner <t.wagner@techdivision.com>
 * @copyright 2016 TechDivision GmbH <info@techdivision.com>
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link      https://github.com/techdivision/import-product
 * @link      http://www.techdivision.com
 */

namespace TechDivision\Import\Product\Observers;

use TechDivision\Import\Product\Utils\ColumnKeys;
use TechDivision\Import\Product\Utils\CoreConfigDataKeys;
use TechDivision\Import\Product\Utils\MemberNames;
use TechDivision\Import\Utils\EntityStatus;
use TechDivision\Import\Utils\EntityTypeCodes;
use TechDivision\Import\Product\Utils\VisibilityKeys;
use TechDivision\Import\Utils\StoreViewCodes;

/**
 * Test class for the product URL rewrite update observer implementation.
 *
 * @author    Tim Wagner <t.wagner@techdivision.com>
 * @copyright 2016 TechDivision GmbH <info@techdivision.com>
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link      https://github.com/techdivision/import-product
 * @link      http://www.techdivision.com
 */
class UrlRewriteUpdateObserverTest extends \PHPUnit_Framework_TestCase
{

    /**
     * The observer we want to test.
     *
     * @var \TechDivision\Import\Product\Observers\UrlRewriteUpdateObserver
     */
    protected $observer;

    /**
     * A mock processor instance.
     *
     * @var \TechDivision\Import\Product\Services\ProductBunchProcessorInterface
     */
    protected $mockProductBunchProcessor;

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     * @see \PHPUnit_Framework_TestCase::setUp()
     */
    protected function setUp()
    {

        // initialize a mock processor instance
        $this->mockProductBunchProcessor = $this->getMockBuilder('TechDivision\Import\Product\Services\ProductBunchProcessorInterface')
                                                ->setMethods(get_class_methods('TechDivision\Import\Product\Services\ProductBunchProcessorInterface'))
                                                ->getMock();

        // initialize the observer
        $this->observer = new UrlRewriteUpdateObserver($this->mockProductBunchProcessor);
    }

    /**
     * Test's the handle() method with a successfull URL rewrite persist when using different categories.
     *
     * @return void
     */
    public function testHandleWithSuccessfullUpdateAndDifferentCategories()
    {

        // initialize the entity ID to use
        $entityId = 61413;

        // create a dummy CSV file row
        $headers = array(
            'sku'             => 0,
            'url_key'         => 1,
            'categories'      => 2,
            'store_view_code' => 3,
            'visibility'      => 4
        );

        // create a dummy CSV file header
        $row = array(
            0 => 'TEST-01',
            1 => 'bruno-compete-hoodie',
            2 => 'Default Category/Men/Bottoms/Pants,Default Category/Collections/Erin Recommends,Default Category',
            3 => $storeViewCode = 'default',
            4 => 'Catalog, Search'
        );

        // the found URL rewrites
        $urlRewrites = array(
            array(
                MemberNames::URL_REWRITE_ID   => 744,
                MemberNames::ENTITY_TYPE      => 'product',
                MemberNames::ENTITY_ID        => $entityId,
                MemberNames::REQUEST_PATH     => sprintf('%s-old.html', $row[$headers[ColumnKeys::URL_KEY]]),
                MemberNames::TARGET_PATH      => sprintf('catalog/product/view/id/%s', $entityId),
                MemberNames::REDIRECT_TYPE    => 0,
                MemberNames::STORE_ID         => 1,
                MemberNames::DESCRIPTION      => null,
                MemberNames::IS_AUTOGENERATED => 1,
                MemberNames::METADATA         => null
            ),
            array(
                MemberNames::URL_REWRITE_ID   => 745,
                MemberNames::ENTITY_TYPE      => 'product',
                MemberNames::ENTITY_ID        => $entityId,
                MemberNames::REQUEST_PATH     => sprintf('men/tops-men/hoodies-and-sweatshirts-men/%s-old.html', $row[$headers[ColumnKeys::URL_KEY]]),
                MemberNames::TARGET_PATH      => sprintf('catalog/product/view/id/%s/category/16', $entityId),
                MemberNames::REDIRECT_TYPE    => 0,
                MemberNames::STORE_ID         => 1,
                MemberNames::DESCRIPTION      => null,
                MemberNames::IS_AUTOGENERATED => 1,
                MemberNames::METADATA         => serialize(array('category_id' => 16))
            ),
            array(
                MemberNames::URL_REWRITE_ID   => 746,
                MemberNames::ENTITY_TYPE      => 'product',
                MemberNames::ENTITY_ID        => $entityId,
                MemberNames::REQUEST_PATH     => sprintf('collections/eco-friendly/%s-old.html', $row[$headers[ColumnKeys::URL_KEY]]),
                MemberNames::TARGET_PATH      => sprintf('catalog/product/view/id/%s/category/37', $entityId),
                MemberNames::REDIRECT_TYPE    => 0,
                MemberNames::STORE_ID         => 1,
                MemberNames::DESCRIPTION      => null,
                MemberNames::IS_AUTOGENERATED => 1,
                MemberNames::METADATA         => serialize(array('category_id' => 37))
            ),
            array(
                MemberNames::URL_REWRITE_ID   => 747,
                MemberNames::ENTITY_TYPE      => 'product',
                MemberNames::ENTITY_ID        => $entityId,
                MemberNames::REQUEST_PATH     => sprintf('men/tops-men/%s-old.html', $row[$headers[ColumnKeys::URL_KEY]]),
                MemberNames::TARGET_PATH      => sprintf('catalog/product/view/id/%s/category/13', $entityId),
                MemberNames::REDIRECT_TYPE    => 0,
                MemberNames::STORE_ID         => 1,
                MemberNames::DESCRIPTION      => null,
                MemberNames::IS_AUTOGENERATED => 1,
                MemberNames::METADATA         => serialize(array('category_id' => 13))
            )
        );

        // create a mock subject
        $mockSubject = $this->getMockBuilder('TechDivision\Import\Product\Subjects\BunchSubject')
                            ->setMethods(
                                    array(
                                        'hasHeader',
                                        'getHeader',
                                        'getHeaders',
                                        'getLastEntityId',
                                        'getProductCategoryIds',
                                        'getRootCategory',
                                        'getRowStoreId',
                                        'getCategory',
                                        'getCoreConfigData',
                                        'getEntityType',
                                        'getRow',
                                        'hasBeenProcessed',
                                        'addEntityIdVisibilityIdMapping',
                                        'getEntityIdVisibilityIdMapping',
                                        'getStoreViewCode'
                                    )
                                )
                                ->disableOriginalConstructor()
                                ->getMock();
        $mockSubject->expects($this->any())
                    ->method('getHeaders')
                    ->willReturn($headers);
        $mockSubject->expects($this->any())
                    ->method('getRow')
                    ->willReturn($row);
        $mockSubject->expects($this->any())
                    ->method('hasHeader')
                    ->willReturn(true);
        $mockSubject->expects($this->any())
                    ->method('getHeader')
                    ->withConsecutive(
                        array(ColumnKeys::STORE_VIEW_CODE),
                        array(ColumnKeys::SKU),
                        array(ColumnKeys::VISIBILITY),
                        array(ColumnKeys::URL_KEY),
                        array(ColumnKeys::URL_KEY),
                        array(ColumnKeys::STORE_VIEW_CODE)
                    )
                    ->willReturnOnConsecutiveCalls(0, 3, 4, 1, 1, 2);
        $mockSubject->expects($this->once())
                    ->method('hasBeenProcessed')
                    ->willReturn(false);
        $mockSubject->expects($this->any())
                    ->method('getLastEntityId')
                    ->willReturn($entityId);
        $mockSubject->expects($this->exactly(5))
                    ->method('getCategory')
                    ->withConsecutive(array(19), array(35), array(19), array(35), array(2))
                    ->willReturnOnConsecutiveCalls(
                        array(MemberNames::ENTITY_ID => 19, MemberNames::PARENT_ID => 1, MemberNames::IS_ANCHOR => null, MemberNames::URL_PATH => 'men/bottoms-men/pants-men'),
                        array(MemberNames::ENTITY_ID => 35, MemberNames::PARENT_ID => 1, MemberNames::IS_ANCHOR => null, MemberNames::URL_PATH => 'collections/erin-recommends'),
                        array(MemberNames::ENTITY_ID => 19, MemberNames::PARENT_ID => 1, MemberNames::IS_ANCHOR => null, MemberNames::URL_PATH => 'men/bottoms-men/pants-men'),
                        array(MemberNames::ENTITY_ID => 35, MemberNames::PARENT_ID => 1, MemberNames::IS_ANCHOR => null, MemberNames::URL_PATH => 'collections/erin-recommends'),
                        array(MemberNames::ENTITY_ID =>  2, MemberNames::PARENT_ID => 1, MemberNames::IS_ANCHOR => null, MemberNames::URL_PATH => null)
                    );
        $mockSubject->expects($this->any())
                    ->method('getRootCategory')
                    ->willReturn(array(MemberNames::ENTITY_ID =>  2, MemberNames::PARENT_ID => 1, MemberNames::IS_ANCHOR => null, MemberNames::URL_PATH => null));
        $mockSubject->expects($this->once())
                    ->method('getStoreViewCode')
                    ->with(StoreViewCodes::ADMIN)
                    ->willReturn($storeViewCode);
        $mockSubject->expects($this->once())
                    ->method('getProductCategoryIds')
                    ->willReturn(array(19 => $entityId, 35 => $entityId));
        $mockSubject->expects($this->once())
                    ->method('getEntityIdVisibilityIdMapping')
                    ->willReturn(VisibilityKeys::VISIBILITY_BOTH);
        $mockSubject->expects($this->any())
                    ->method('getRowStoreId')
                    ->willReturn($storeId = 1);
        $mockSubject->expects($this->exactly(10))
                    ->method('getCoreConfigData')
                    ->withConsecutive(
                        array(CoreConfigDataKeys::CATALOG_SEO_PRODUCT_USE_CATEGORIES, false),
                        array(CoreConfigDataKeys::CATALOG_SEO_PRODUCT_URL_SUFFIX, '.html'),
                        array(CoreConfigDataKeys::CATALOG_SEO_PRODUCT_URL_SUFFIX, '.html'),
                        array(CoreConfigDataKeys::CATALOG_SEO_PRODUCT_URL_SUFFIX, '.html'),
                        array(CoreConfigDataKeys::CATALOG_SEO_SAVE_REWRITES_HISTORY, true),
                        array(CoreConfigDataKeys::CATALOG_SEO_PRODUCT_URL_SUFFIX, '.html'),
                        array(CoreConfigDataKeys::CATALOG_SEO_SAVE_REWRITES_HISTORY, true),
                        array(CoreConfigDataKeys::CATALOG_SEO_PRODUCT_URL_SUFFIX, '.html'),
                        array(CoreConfigDataKeys::CATALOG_SEO_SAVE_REWRITES_HISTORY, true),
                        array(CoreConfigDataKeys::CATALOG_SEO_PRODUCT_URL_SUFFIX, '.html')
                    )
                    ->willReturnOnConsecutiveCalls(true, '.html', '.html', '.html', true, '.html', true, '.html', true, '.html', '.html');
        $mockSubject->expects($this->exactly(1))
                    ->method('getEntityType')
                    ->willReturn(array(MemberNames::ENTITY_TYPE_ID => 1, MemberNames::ENTITY_TYPE_CODE => EntityTypeCodes::CATALOG_PRODUCT));

        // mock the processor methods
        $this->mockProductBunchProcessor->expects($this->any())
                    ->method('loadUrlRewriteProductCategory')
                    ->willReturn(array());
        $this->mockProductBunchProcessor->expects($this->once())
                    ->method('getUrlRewritesByEntityTypeAndEntityIdAndStoreId')
                    ->with(UrlRewriteObserver::ENTITY_TYPE, $entityId, $storeId)
                    ->willReturn($urlRewrites);
        $this->mockProductBunchProcessor->expects($this->exactly(6))
                    ->method('persistUrlRewrite')
                    ->withConsecutive(
                        array(
                            array(
                                EntityStatus::MEMBER_NAME     => EntityStatus::STATUS_CREATE,
                                MemberNames::ENTITY_TYPE      => UrlRewriteObserver::ENTITY_TYPE,
                                MemberNames::ENTITY_ID        => $entityId,
                                MemberNames::REQUEST_PATH     => sprintf('men/bottoms-men/pants-men/%s.html', $row[$headers[ColumnKeys::URL_KEY]]),
                                MemberNames::TARGET_PATH      => sprintf('catalog/product/view/id/%d/category/%d', $entityId, 19),
                                MemberNames::REDIRECT_TYPE    => 0,
                                MemberNames::STORE_ID         => $storeId,
                                MemberNames::DESCRIPTION      => null,
                                MemberNames::IS_AUTOGENERATED => 1,
                                MemberNames::METADATA         => serialize(array('category_id' => 19))
                            )
                        ),
                        array(
                            array(
                                EntityStatus::MEMBER_NAME     => EntityStatus::STATUS_CREATE,
                                MemberNames::ENTITY_TYPE      => UrlRewriteObserver::ENTITY_TYPE,
                                MemberNames::ENTITY_ID        => $entityId,
                                MemberNames::REQUEST_PATH     => sprintf('collections/erin-recommends/%s.html', $row[$headers[ColumnKeys::URL_KEY]]),
                                MemberNames::TARGET_PATH      => sprintf('catalog/product/view/id/%d/category/%d', $entityId, 35),
                                MemberNames::REDIRECT_TYPE    => 0,
                                MemberNames::STORE_ID         => $storeId,
                                MemberNames::DESCRIPTION      => null,
                                MemberNames::IS_AUTOGENERATED => 1,
                                MemberNames::METADATA         => serialize(array('category_id' => 35))
                            )
                        ),
                        array(
                            array(
                                EntityStatus::MEMBER_NAME     => EntityStatus::STATUS_UPDATE,
                                MemberNames::ENTITY_TYPE      => UrlRewriteObserver::ENTITY_TYPE,
                                MemberNames::URL_REWRITE_ID   => 744,
                                MemberNames::ENTITY_ID        => $entityId,
                                MemberNames::REQUEST_PATH     => sprintf('%s.html', $row[$headers[ColumnKeys::URL_KEY]]),
                                MemberNames::TARGET_PATH      => sprintf('catalog/product/view/id/%s', $entityId),
                                MemberNames::REDIRECT_TYPE    => 0,
                                MemberNames::STORE_ID         => $storeId,
                                MemberNames::DESCRIPTION      => null,
                                MemberNames::IS_AUTOGENERATED => 1,
                                MemberNames::METADATA         => serialize(array())
                            )
                        ),
                        array(
                            array(
                                EntityStatus::MEMBER_NAME     => EntityStatus::STATUS_UPDATE,
                                MemberNames::ENTITY_TYPE      => UrlRewriteObserver::ENTITY_TYPE,
                                MemberNames::URL_REWRITE_ID   => 745,
                                MemberNames::ENTITY_ID        => $entityId,
                                MemberNames::REQUEST_PATH     => sprintf('men/tops-men/hoodies-and-sweatshirts-men/%s-old.html', $row[$headers[ColumnKeys::URL_KEY]]),
                                MemberNames::TARGET_PATH      => sprintf('%s.html', $row[$headers[ColumnKeys::URL_KEY]]),
                                MemberNames::REDIRECT_TYPE    => 301,
                                MemberNames::STORE_ID         => $storeId,
                                MemberNames::DESCRIPTION      => null,
                                MemberNames::IS_AUTOGENERATED => 0,
                                MemberNames::METADATA         => serialize(array())
                            )
                        ),
                        array(
                            array(
                                EntityStatus::MEMBER_NAME     => EntityStatus::STATUS_UPDATE,
                                MemberNames::ENTITY_TYPE      => UrlRewriteObserver::ENTITY_TYPE,
                                MemberNames::URL_REWRITE_ID   => 746,
                                MemberNames::ENTITY_ID        => $entityId,
                                MemberNames::REQUEST_PATH     => sprintf('collections/eco-friendly/%s-old.html', $row[$headers[ColumnKeys::URL_KEY]]),
                                MemberNames::TARGET_PATH      => sprintf('%s.html', $row[$headers[ColumnKeys::URL_KEY]]),
                                MemberNames::REDIRECT_TYPE    => 301,
                                MemberNames::STORE_ID         => $storeId,
                                MemberNames::DESCRIPTION      => null,
                                MemberNames::IS_AUTOGENERATED => 0,
                                MemberNames::METADATA         => serialize(array())
                            )
                        ),
                        array(
                            array(
                                EntityStatus::MEMBER_NAME     => EntityStatus::STATUS_UPDATE,
                                MemberNames::ENTITY_TYPE      => UrlRewriteObserver::ENTITY_TYPE,
                                MemberNames::URL_REWRITE_ID   => 747,
                                MemberNames::ENTITY_ID        => $entityId,
                                MemberNames::REQUEST_PATH     => sprintf('men/tops-men/%s-old.html', $row[$headers[ColumnKeys::URL_KEY]]),
                                MemberNames::TARGET_PATH      => sprintf('%s.html', $row[$headers[ColumnKeys::URL_KEY]]),
                                MemberNames::REDIRECT_TYPE    => 301,
                                MemberNames::STORE_ID         => $storeId,
                                MemberNames::DESCRIPTION      => null,
                                MemberNames::IS_AUTOGENERATED => 0,
                                MemberNames::METADATA         => serialize(array())
                            )
                        )
                    )
                    ->willReturnOnConsecutiveCalls(1000, 1001, 1002, 1003, 1004, 1005, 1006);
        $this->mockProductBunchProcessor->expects($this->exactly(3))
                    ->method('persistUrlRewriteProductCategory')
                    ->withConsecutive(
                        array(
                            array(
                                MemberNames::URL_REWRITE_ID   => 1000,
                                MemberNames::PRODUCT_ID       => $entityId,
                                MemberNames::CATEGORY_ID      => 19,
                                EntityStatus::MEMBER_NAME     => EntityStatus::STATUS_CREATE
                            )
                        ),
                        array(
                            array(
                                MemberNames::URL_REWRITE_ID   => 1001,
                                MemberNames::PRODUCT_ID       => $entityId,
                                MemberNames::CATEGORY_ID      => 35,
                                EntityStatus::MEMBER_NAME     => EntityStatus::STATUS_CREATE
                            )
                        ),
                        array(
                            array(
                                MemberNames::URL_REWRITE_ID   => 1002,
                                MemberNames::PRODUCT_ID       => $entityId,
                                MemberNames::CATEGORY_ID      => 2,
                                EntityStatus::MEMBER_NAME     => EntityStatus::STATUS_CREATE
                            )
                        )
                    );

        // invoke the handle() method
        $this->assertSame($row, $this->observer->handle($mockSubject));
    }
}
